[project]
name = "multi-agents"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Hafiz Rizwan", email = "hafizmr7788@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "crewai[google-genai]>=1.15.1",
    "python-dotenv>=1.2.2",
]

[project.scripts]
multi-agents = "multi_agents.main:kickoff"

[build-system]
requires = ["uv_build>=0.11.25,<0.12.0"]
build-backend = "uv_build"
