from crewai import Agent, Crew, Task
from crewai.project import CrewBase, agent, crew, task
from crewai import Process


@CrewBase
class DevCrew2():
    
    @agent
    def junior_python_developer(self):
        return Agent(
            role="Junior Python Developer",
            goal="Write the python code of this {problem} and do not write any type hinting and pydocs",
            backstory="You are a junior python developer who is learning to write code. You are given a problem and you need to write the code for it. You should not write any type hinting or pydocs. You should only write the code."
        )

    @agent
    def senior_python_developer(self):
        return Agent(
            role="Senior Python Developer",
            goal="""Review the python code and perform the following tasks on it:
                    1) Optimize the code
                    2) apply type hinting
                    3) apply pydocs
                    4) Provide 3 pytests""",
            backstory="""You are a Senior Python Developer with more than 10 years of professional
                        experience building scalable, maintainable, and high-performance Python
                        applications. You have extensive knowledge of Python best practices,
                        software design principles, clean code, testing, and optimization.
                        Your responsibility is to carefully review the code written by junior
                        developers, improve its readability, efficiency, and maintainability,
                        add appropriate type hints and comprehensive docstrings, and create
                        reliable pytest test cases to verify the correctness of the solution.
                        You always preserve the original functionality while making the code
                        production-ready and easy for other developers to understand."""
        )


    @task
    def code_generation(self):
        return Task(
            description="""Write a Python solution for the following problem:
                        {problem}
                        Requirements:
                        - Write only the Python code.
                        - Do not add type hints.
                        - Do not add docstrings.
                        - Keep the solution simple and readable.
                        - Do not include any explanation or markdown.""",
            expected_output="A complete Python solution containing only executable Python code.",
            agent=self.junior_python_developer()
        )
    

    @task
    def code_review(self):
        return Task(
            description="""Review the Python code generated by the junior developer.
                            Perform the following improvements:
                            1. Optimize the code wherever possible.
                            2. Add appropriate type hints.
                            3. Add meaningful docstrings.
                            4. Follow Python best practices (PEP 8).
                            5. Improve readability and maintainability.
                            6. Preserve the original functionality.
                            7. Write three pytest test cases that validate the solution.

                            Review the code provided as context.""",
            expected_output="""Return:
                                1. The improved Python code.
                                2. Three pytest test cases.""",
            agent=self.senior_python_developer()
        )
    
    
    @crew
    def crew(self):
        return Crew(
            agents=self.agents,
            tasks=self.tasks,
            process=Process.sequential,
            verbose=True,
        )